### ISSUE TITLE
permission denied for supervisord on MacOS

### ISSUE THREAD

**Issue by mostalive** [qwaneu/distributed-ensemble#1]
As reported on the technical coaching discord. In Docker Desktop on Mac:

```
Attaching to distributed-ensemble-exercise_desktop-1
distributed-ensemble-exercise_desktop-1  | + RUN_FLUXBOX=yes
distributed-ensemble-exercise_desktop-1  | + 
RUN_XTERM=yes
distributed-ensemble-exercise_desktop-1  | + case $RUN_FLUXBOX in
distributed-ensemble-exercise_desktop-1  | + case $RUN_XTERM in
distributed-ensemble-exercise_desktop-1  | + exec supervisord -c /app/supervisord.conf
[...]
File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 160, in __init__
distributed-ensemble-exercise_desktop-1  |     self.stream = open(filename, mode)
distributed-ensemble-exercise_desktop-1  | PermissionError: [Errno 13] Permission denied: '/home/experience/supervisord.log'
distributed-ensemble-exercise_desktop-1 exited with code 1
```

I've reproduced this with colima as welll, so not limited to docker desktop

**Comment by mostalive** [comment]
Thinking out loud, may be something with setting the users. running the CMD /app/entrypoint.sh after logging in by hand does not crash:

```
docker run -it distributed-ensemble-exercise_desktop  /bin/bash
experience@6462244f7563:~$ /app/entrypoint.sh
```

2023-05-05 14:29:36,315 INFO Included extra file "/app/conf.d/fluxbox.conf" during parsing
2023-05-05 14:29:36,315 INFO Included extra file "/app/conf.d/idea.conf" during parsing
2023-05-05 14:29:36,315 INFO Included extra file "/app/conf.d/websockify.conf" during parsing
2023-05-05 14:29:36,315 INFO Included extra file "/app/conf.d/x11vnc.conf" during parsing
2023-05-05 14:29:36,315 INFO Included extra file "/app/conf.d/xterm.conf" during parsing
2023-05-05 14:29:36,315 INFO Included extra file "/app/conf.d/xvfb.conf" during parsing
2023-05-05 14:29:36,318 INFO supervisord started with pid 12
2023-05-05 14:29:37,322 INFO spawned: 'fluxbox' with pid 13
2023-05-05 14:29:37,324 INFO spawned: 'idea' with pid 14
2023-05-05 14:29:37,326 INFO spawned: 'websockify' with pid 15
2023-05-05 14:29:37,328 INFO spawned: 'x11vnc' with pid 16
2023-05-05 14:29:37,329 INFO spawned: 'xterm' with pid 23
2023-05-05 14:29:37,331 INFO spawned: 'xvfb' with pid 27
2023-05-05 14:29:37,344 WARN exited: fluxbox (exit status 1; not expected)
2023-05-05 14:29:37,347 WARN exited: xterm (exit status 1; not expected)
2023-05-05 14:29:38,358 INFO spawned: 'fluxbox' with pid 97
2023-05-05 14:29:38,358 INFO success: idea entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-05-05 14:29:38,358 INFO success: websockify entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-05-05 14:29:38,358 INFO success: x11vnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-05-05 14:29:38,360 INFO spawned: 'xterm' with pid 98
2023-05-05 14:29:38,360 INFO success: xvfb entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-05-05 14:29:39,648 INFO success: fluxbox entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-05-05 14:29:39,648 INFO success: xterm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

**Comment by mostalive** [comment]
it appears the username is not set. Added 'debug-ensemble.sh' to start a prompt instead of the entrypoint, so that we can start it by hand and continue debugging.

```
./debug-ensemble.sh java-intellij
+ export language=java-intellij
+ language=java-intellij
+ [[ java-intellij == '' ]]
++ dirname ./debug-ensemble.sh
+ export CLIDIR=.
+ CLIDIR=.
++ id -u
+ export MY_UID=501
+ MY_UID=501
++ id -g
+ export MY_GID=20
+ MY_GID=20
++ pwd
+ export CURDIR=/Users/willem/MyDocuments/qwan/infra/distributed-ensemble
+ CURDIR=/Users/willem/MyDocuments/qwan/infra/distributed-ensemble
+ docker-compose -f ./exercise-container.yml run exercise_desktop /bin/bash
I have no name!@a0bebabc1caf:~$ /app/entrypoint.sh 
+ RUN_FLUXBOX=yes
+ RUN_XTERM=yes
+ case $RUN_FLUXBOX in
+ case $RUN_XTERM in
+ exec supervisord -c /app/supervisord.conf
Traceback (most recent call last):
  File "/usr/bin/supervisord", line 33, in <module>
    sys.exit(load_entry_point('supervisor==4.2.5', 'console_scripts', 'supervisord')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/supervisor/supervisord.py", line 359, in main
    go(options)
  File "/usr/lib/python3/dist-packages/supervisor/supervisord.py", line 369, in go
    d.main()
  File "/usr/lib/python3/dist-packages/supervisor/supervisord.py", line 72, in main
    self.options.make_logger()
  File "/usr/lib/python3/dist-packages/supervisor/options.py", line 1488, in make_logger
    loggers.handle_file(
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 419, in handle_file
    handler = RotatingFileHandler(filename, 'a', maxbytes, backups)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 213, in __init__
    FileHandler.__init__(self, filename, mode)
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 160, in __init__
    self.stream = open(filename, mode)
                  ^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/home/experience/supervisord.log'
I have no name!@a0bebabc1caf:~$ 
```

running `whoami`:

```
 whoami
whoami: cannot find name for user ID 501
```

**Comment by mostalive** [comment]
A workaround might be to set the hosts uid in the `desktop-base/Dockerfile`, add the -u flag like so (501 is my UID)

```
RUN useradd -u 501 experience -s /bin/bash  -m -k /etc/skel
```

but that makes it unflexible for deploying to a server etc.

**Comment by mostalive** [comment]
As a workaround, I added `./demo.sh` which will add the exercises to another docker image, and build the layers up to that image as well. Finally it runs the final docker image, only opening the port, not mounting local directories.

**Comment by mostalive** [comment]
Keeping the workaround for now, volume mounting will come back later - once we can build reliably on Mac (m1 and intel, see #2).
